### ISSUE TITLE
Reloader

### ISSUE THREAD

**Issue by embrake** [nggit/tremolo#26]
Hey I really like this project and appreciate your work, but can you also add a reloader when detect code changes it really helps the server to become more vast, I hope you you got my point, you can use further libraries like watchdog and etc..

**Comment by nggit** [comment]
Hello. Thanks for evaluating this project.

I have added the reload functionality in [v0.0.206](https://github.com/nggit/tremolo/pull/27) (already available on PyPI).

Due to the project philosophy, external libraries were not adopted for this kind of small feature :)

**Comment by nggit** [comment]
Whoa, a year has passed and [many changes have been made](https://github.com/nggit/tremolo/compare/cb169e3...main). I believe this issue is no longer applicable in the latest version, [0.0.755](https://github.com/nggit/tremolo/tree/7dc4edb70c1b7d1b2448138f1d72390a6fc3a755).

So I'm closing it now. Thank you.
